curl -X 'POST' \
  'http://174.138.119.239.nip.io/sessions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "kind": "spark",
  "proxyUser": "david"
}'

curl -X 'GET' \
  'http://174.138.119.239.nip.io/sessions' \
  -H 'accept: application/json' \
  -H 'access_token: accesstoken'

curl -X 'GET' \
  'http://174.138.119.239.nip.io/sessions/0' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json'