# Default values for Livy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
livy:
  image:
    repository: jchudb93/livy
    tag: 0.8.0-incubating-spark_3.0.1_2.12-hadoop_3.2.0_cloud
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
  env:
    LIVY_LIVY_IMPERSONATION_ENABLED: {value: "true"}
      
  load_balancer:
    enabled: false
    name:
    port: 80

ingress-nginx:
  controller:
    config: {}

livy-admin:
  kubernetesClusterDomain: cluster.local
  livyAdmin:
    livyAdmin:
      image:
        repository: jchudb93/livy-admin 
        tag: latest
      apiKey: 55d51bedde21
      livyServer: http://livy-server.livy.svc.cluster.local
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
    replicas: 1
  service:
    ports:
    - port: 80
      targetPort: 80
    type: NodePort
  ingress:
    spec:
      host: 167.99.21.118.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx
      