# Default values for Livy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
livy:
  service:
    type: NodePort
    port: 80
  env:
    LIVY_LIVY_IMPERSONATION_ENABLED: {value: "true"}

  ingress:
    enabled: false
  path: /livy/?(.*)
  hosts:
    - livy.local

  load_balancer:
    enabled: true
    name:
    port: 80