# Default values for Livy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
livy:
  service:
    type: NodePort
    port: 80
  env:
    LIVY_LIVY_IMPERSONATION_ENABLED: {value: "true"}

  ingress:
    enabled: true
    path: /
    hosts:
      - 144.126.248.21.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      


  load_balancer:
    enabled: false
    name:
    port: 80