apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "livy-admin.fullname" . }}-ingress
  labels:
  {{- include "livy-admin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  rules:
  - host:  {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "livy-admin.fullname" . }}-service'
            port:
              number: 80
        path: /
        pathType: Prefix