apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy-admin.fullname" . }}-service
  labels:
  {{- include "livy-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: livy-admin
  {{- include "livy-admin.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}